backend:
  name: github
  repo: bryankek/bk-base # replace this with your repo info

media_folder: media_folder

collections:
- name: post
label: Post
folder: posts
create: true
fields:
  - {name: title, label: Title}
  - {name: body, label: Body, widget: markdown}