backend:
  name: github
  repo: bryankek/bk-base # replace this with your repo info
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
site_url: https://bryankek.xyz

collections:
- name: post
label: Post
folder: posts
create: true
fields:
  - {name: title, label: Title}
  - {name: body, label: Body, widget: markdown}
